# Generated by Django 6.0.1 on 2026-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Sarlovha ...', max_length=255, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name="Ma'lumot")),
                ('is_trashed', models.BooleanField(default=False, verbose_name='Korzina')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
